# version: '3'

# services:
#   ollama:
#     image: ollama/ollama:latest
#     container_name: ollama
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama_data:/root/.ollama
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

#   tender-analyzer:
#     build: .
#     container_name: tender-analyzer
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./uploads:/app/uploads
#       - ./output:/app/output
#     environment:
#       - OLLAMA_API_BASE=http://ollama:11434
#     restart: unless-stopped
#     depends_on:
#       ollama:
#         condition: service_healthy

# volumes:
#   ollama_data: 

version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 120s
      timeout: 60s
      retries: 5

  tender-analyzer:
    image: IMAGE_PLACEHOLDER
    container_name: tender-analyzer
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama_data:
